#!/bin/bash

set -e

if [ $# -ne 1 -o ! -f "$1" ]; then
  echo "Usage: $0 <path to APK>" >&2
  exit 1
fi

apktool d -o workdir -f "$1"

python merge_lang.py -o workdir/assets/lang/en_US.lang workdir/assets/lang/en_US.lang tl.lang
